// <auto-generated />
using DoubleDbProvider.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace DoubleDbProvider.Domain.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Todos")
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoubleDbProvider.Domain.Models.Kind", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Kinds");
                });

            modelBuilder.Entity("DoubleDbProvider.Domain.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<decimal>("Cost")
                        .HasColumnType("smallmoney");

                    b.Property<DateTimeOffset>("CreateDate");

                    b.Property<short?>("KindId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("KindId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("DoubleDbProvider.Domain.Models.Todo", b =>
                {
                    b.HasOne("DoubleDbProvider.Domain.Models.Kind", "Kind")
                        .WithMany("Todos")
                        .HasForeignKey("KindId");
                });
#pragma warning restore 612, 618
        }
    }
}
